spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nulp
    username: postgres
    password: root1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
